//! Separable orthonormal DCT-II (f64 reference) — spec section 7.
//!
//! Loop order is normative for bit-exactness (spec section 7.1) and mirrors
//! src/refdec.py exactly. An integer exact-match transform is future work.

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

fn matrix_cache() -> &'static Mutex<HashMap<usize, Vec<f64>>> {
    static CACHE: OnceLock<Mutex<HashMap<usize, Vec<f64>>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

/// DCT-II matrix, row-major: m[k*n + nn].
pub fn dct_matrix(n: usize) -> Vec<f64> {
    {
        let cache = matrix_cache().lock().unwrap();
        if let Some(m) = cache.get(&n) {
            return m.clone();
        }
    }
    let mut m = vec![0.0f64; n * n];
    let s = (2.0 / n as f64).sqrt();
    let inv_sqrt2 = 1.0 / 2.0f64.sqrt();
    for k in 0..n {
        let ck = if k == 0 { inv_sqrt2 } else { 1.0 };
        for nn in 0..n {
            m[k * n + nn] =
                s * ck * ((std::f64::consts::PI * (2 * nn + 1) as f64 * k as f64)
                    / (2 * n) as f64)
                    .cos();
        }
    }
    matrix_cache().lock().unwrap().insert(n, m.clone());
    m
}

/// Forward orthonormal DCT-II: F = M * x * M^T. Loop order per spec 7.1
/// (mirrors the Python reference bit-exactly).
pub fn dct_forward(block: &[f64], n: usize) -> Vec<f64> {
    let m = dct_matrix(n);
    // T = M @ x
    let mut t = vec![0.0f64; n * n];
    for i in 0..n {
        for j in 0..n {
            let mut s = 0.0;
            for nn in 0..n {
                s += m[i * n + nn] * block[nn * n + j];
            }
            t[i * n + j] = s;
        }
    }
    // F = T @ M^T
    let mut f = vec![0.0f64; n * n];
    for i in 0..n {
        for j in 0..n {
            let mut s = 0.0;
            for nn in 0..n {
                s += t[i * n + nn] * m[j * n + nn];
            }
            f[i * n + j] = s;
        }
    }
    f
}

/// Inverse orthonormal DCT-II: x = M^T * F * M. Loop order per spec 7.1.
pub fn dct_inverse(coeffs: &[f64], n: usize) -> Vec<f64> {
    let m = dct_matrix(n);
    // T = M^T @ F
    let mut t = vec![0.0f64; n * n];
    for i in 0..n {
        for j in 0..n {
            let mut s = 0.0;
            for nn in 0..n {
                s += m[nn * n + i] * coeffs[nn * n + j];
            }
            t[i * n + j] = s;
        }
    }
    // x = T @ M
    let mut x = vec![0.0f64; n * n];
    for i in 0..n {
        for j in 0..n {
            let mut s = 0.0;
            for nn in 0..n {
                s += t[i * n + nn] * m[nn * n + j];
            }
            x[i * n + j] = s;
        }
    }
    x
}

/// JPEG-style diagonal zigzag scan order, spec section 8.
/// Returns a static slice for the 4 supported sizes (no allocation, no lock).
pub fn zigzag(n: usize) -> &'static [(usize, usize)] {
    match n {
        4 => &ZIGZAG4,
        8 => &ZIGZAG8,
        16 => zigzag16(),
        32 => zigzag32(),
        _ => panic!("unsupported zigzag size"),
    }
}

const ZIGZAG4: [(usize, usize); 16] = [
    (0,0),(0,1),(1,0),(2,0),(1,1),(0,2),(0,3),(1,2),
    (2,1),(3,0),(3,1),(2,2),(1,3),(2,3),(3,2),(3,3),
];

const ZIGZAG8: [(usize, usize); 64] = [
    (0,0),(0,1),(1,0),(2,0),(1,1),(0,2),(0,3),(1,2),
    (2,1),(3,0),(4,0),(3,1),(2,2),(1,3),(0,4),(0,5),
    (1,4),(2,3),(3,2),(4,1),(5,0),(6,0),(5,1),(4,2),
    (3,3),(2,4),(1,5),(0,6),(0,7),(1,6),(2,5),(3,4),
    (4,3),(5,2),(6,1),(7,0),(7,1),(6,2),(5,3),(4,4),
    (3,5),(2,6),(1,7),(2,7),(3,6),(4,5),(5,4),(6,3),
    (7,2),(7,3),(6,4),(5,5),(4,6),(3,7),(4,7),(5,6),
    (6,5),(7,4),(7,5),(6,6),(5,7),(6,7),(7,6),(7,7),
];

// Generated at compile time via const fn would be ideal; for now, use lazy static arrays.
// ZIGZAG16 and ZIGZAG32 are generated by the build script or computed once.
// For simplicity, we compute them on first use with a lock-free OnceLock<Vec>.
static ZIGZAG16_VEC: OnceLock<Vec<(usize, usize)>> = OnceLock::new();
static ZIGZAG32_VEC: OnceLock<Vec<(usize, usize)>> = OnceLock::new();

fn zigzag16() -> &'static [(usize, usize)] {
    ZIGZAG16_VEC.get_or_init(|| gen_zigzag(16))
}
fn zigzag32() -> &'static [(usize, usize)] {
    ZIGZAG32_VEC.get_or_init(|| gen_zigzag(32))
}

fn gen_zigzag(n: usize) -> Vec<(usize, usize)> {
    let mut order = Vec::with_capacity(n * n);
    for s in 0..(2 * n - 1) {
        if s % 2 == 0 {
            let (mut r, mut c) = (s.min(n - 1) as isize, (s - s.min(n - 1)) as isize);
            while r >= 0 && c < n as isize {
                order.push((r as usize, c as usize));
                r -= 1;
                c += 1;
            }
        } else {
            let (mut c, mut r) = (s.min(n - 1) as isize, (s - s.min(n - 1)) as isize);
            while c >= 0 && r < n as isize {
                order.push((r as usize, c as usize));
                r += 1;
                c -= 1;
            }
        }
    }
    order
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zigzag_2x2() {
        assert_eq!(zigzag(2), vec![(0, 0), (0, 1), (1, 0), (1, 1)]);
    }

    #[test]
    fn idct_of_zero_is_zero() {
        let z = vec![0.0; 1024];
        let x = dct_inverse(&z, 32);
        assert!(x.iter().all(|&v| v == 0.0));
    }
}
